package queen.s.cab.services;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Siddharth
 */
public final class customerHome extends javax.swing.JFrame {

    /**
     * Creates new form customerHome
     */
     Connection conn = null;
     PreparedStatement pst = null;
     ResultSet rs = null;
     public final String c_id ;
        
    public customerHome(String s) throws SQLException {
        c_id = s;
        initComponents();
        loadCustDetails(c_id);
        
        savedPlaces.addItem("Manipal");
        savedPlaces.addItem("Delhi");
        savedPlaces.addItem("Mumbai");
        savedPlaces.addItem("Rewa");
        savedPlaces.addItem("Indore");
    }

    private customerHome() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
     public void loadCustDetails(String s) throws SQLException{
        String query = "Select * from customer where C_EMAIL=?;";
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/se_proj","root","");
        pst = conn.prepareStatement(query);
        pst.setString(1, s);
        rs = pst.executeQuery();
        while(rs.next()){
            name.setText(rs.getString("C_Fname")+" "+rs.getString("C_LNAME"));
            //rCount.setText("Rides Count: "+rs.getString("NO_RIDE"));
            //cPhNo.setText("Contact No.-  "+ rs.getString("C_PH_NO"));
            //sPass.setText("Special Pass: "+ rs.getString("S_PASS"));
            cID.setText(""+rs.getString("C_ID"));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        savedPlaces = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cID = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 562));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 562));
        setSize(new java.awt.Dimension(1000, 562));
        getContentPane().setLayout(null);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(210, 50, 2, 580);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(1000, 562));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 562));
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Microsoft New Tai Lue", 2, 24)); // NOI18N
        jLabel9.setText("Book A Ride!");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(530, 80, 140, 50);

        jTextField1.setFont(new java.awt.Font("Microsoft Tai Le", 3, 14)); // NOI18N
        jTextField1.setText("Pick Up");
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1);
        jTextField1.setBounds(380, 220, 150, 40);

        savedPlaces.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        savedPlaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savedPlacesActionPerformed(evt);
            }
        });
        jPanel3.add(savedPlaces);
        savedPlaces.setBounds(590, 410, 170, 30);

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        jLabel4.setText("Saved Places :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(480, 410, 90, 30);

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        jLabel6.setText("Or");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(580, 330, 30, 18);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(370, 250, 170, 10);

        jPanel1.setBackground(new java.awt.Color(0, 64, 64));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Customer ID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 110, 80, 18);

        cID.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        cID.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(cID);
        cID.setBounds(100, 110, 40, 20);

        name.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Siddharth");
        jPanel1.add(name);
        name.setBounds(10, 60, 150, 30);

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome,");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 18, 60, 20);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(0, 50, 210, 140);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        jLabel2.setText(" Log out");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 310, 60, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\icons\\logout_rounded_left_32px.png")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 310, 100, 40);

        jLabel11.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        jLabel11.setText("Help!");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(60, 260, 90, 40);

        jLabel12.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        jLabel12.setText("Profile");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel12);
        jLabel12.setBounds(50, 20, 90, 30);

        jLabel13.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        jLabel13.setText("Transaction");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(50, 80, 90, 30);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(0, 230, 210, 20);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(0, 200, 210, 360);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\icons\\cancel_48px.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3);
        jLabel3.setBounds(950, 0, 50, 50);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 1000, 50);

        jTextField2.setFont(new java.awt.Font("Microsoft Tai Le", 3, 14)); // NOI18N
        jTextField2.setText("Where to?");
        jTextField2.setBorder(null);
        jTextField2.setOpaque(false);
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(660, 220, 150, 40);
        jPanel3.add(jSeparator3);
        jSeparator3.setBounds(650, 250, 160, 10);

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\icons\\snazzy-image.png")); // NOI18N
        jPanel3.add(jLabel10);
        jLabel10.setBounds(210, 50, 800, 570);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1000, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void savedPlacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savedPlacesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savedPlacesActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new custLoginPage().setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked

        // TODO add your handling code here:
        new custProfile(c_id).setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new customerHome().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel name;
    private javax.swing.JComboBox<String> savedPlaces;
    // End of variables declaration//GEN-END:variables
}
