/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package queen.s.cab.services;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JLabel;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Siddharth
 */
public final class custProfile extends javax.swing.JFrame {

    /**
     * Creates new form custProfile
     * @param cid
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public final String s1;
    public custProfile(String cid){
        s1 = cid;
        initComponents();
        loadDetails(s1);
        hidd.setVisible(false);
    }
    
    public void loadDetails(String id){
        try{
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/se_proj","root","");
        pst = conn.prepareStatement("Select * from customer where C_EMAIL = ? ;");
        pst.setString(1, id);
        rs = pst.executeQuery();
        while(rs.next()){
            text1.setText(rs.getString("C_ID"));
            text2.setText(rs.getString("C_FNAME") + " " + rs.getString("C_LNAME"));
            text3.setText(rs.getString("C_PH_NO"));
            text4.setText(rs.getString("C_EMAIL"));
            text5.setText(rs.getString("NO_RIDE"));
            text6.setText(rs.getString("S_PASS"));
        }
        }
        catch(SQLException e){
            
        }
    }
    

    private custProfile() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    custProfile(JLabel cID) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        text3 = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        text5 = new javax.swing.JLabel();
        text6 = new javax.swing.JLabel();
        text4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        hidd = new javax.swing.JPanel();
        newPass = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        newPass1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 562));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000, 562));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\icons\\cancel_48px.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(953, 0, 50, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\icons\\left_50px.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 50, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 50);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1000, 562));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 562));

        jPanel3.setBackground(new java.awt.Color(0, 64, 64));
        jPanel3.setMinimumSize(new java.awt.Dimension(1000, 562));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 562));
        jPanel3.setVerifyInputWhenFocusTarget(false);
        jPanel3.setLayout(null);

        text3.setFont(new java.awt.Font("Microsoft Tai Le", 2, 18)); // NOI18N
        text3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(text3);
        text3.setBounds(160, 170, 180, 30);

        text1.setFont(new java.awt.Font("Microsoft Tai Le", 2, 18)); // NOI18N
        text1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(text1);
        text1.setBounds(160, 40, 40, 30);

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Special Pass :");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 390, 110, 30);

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer ID :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 40, 120, 30);

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(80, 100, 70, 30);

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact No. :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 170, 110, 30);

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email Address :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 240, 130, 30);

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. Rides :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(40, 320, 100, 30);

        text2.setFont(new java.awt.Font("Microsoft Tai Le", 2, 18)); // NOI18N
        text2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(text2);
        text2.setBounds(160, 100, 180, 30);

        text5.setFont(new java.awt.Font("Microsoft Tai Le", 2, 18)); // NOI18N
        text5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(text5);
        text5.setBounds(160, 320, 180, 30);

        text6.setFont(new java.awt.Font("Microsoft Tai Le", 2, 18)); // NOI18N
        text6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(text6);
        text6.setBounds(160, 390, 180, 30);

        text4.setFont(new java.awt.Font("Microsoft Tai Le", 2, 18)); // NOI18N
        text4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(text4);
        text4.setBounds(160, 240, 180, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(461, 0, 25, 511);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(470, 260, 530, 10);

        hidd.setBackground(new java.awt.Color(0, 64, 64));

        newPass.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        newPass.setForeground(new java.awt.Color(255, 255, 255));
        newPass.setBorder(null);
        newPass.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("New Password");

        jLabel11.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Re-enter");

        jButton1.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("D:\\icons\\submit_for_approval_24px.png")); // NOI18N
        jButton1.setText("Submit");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        newPass1.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        newPass1.setForeground(new java.awt.Color(255, 255, 255));
        newPass1.setBorder(null);
        newPass1.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Microsoft Tai Le", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Change Password");

        javax.swing.GroupLayout hiddLayout = new javax.swing.GroupLayout(hidd);
        hidd.setLayout(hiddLayout);
        hiddLayout.setHorizontalGroup(
            hiddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hiddLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(hiddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hiddLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hiddLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hiddLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hiddLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(newPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hiddLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hiddLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        hiddLayout.setVerticalGroup(
            hiddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hiddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(hiddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(hiddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(hidd);
        hidd.setBounds(470, 20, 520, 230);

        jToggleButton1.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon("D:\\icons\\key_32px.png")); // NOI18N
        jToggleButton1.setText("Change Password");
        jToggleButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.darkGray, java.awt.Color.lightGray));
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jToggleButton1);
        jToggleButton1.setBounds(20, 450, 170, 40);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1000, 562);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!"".equals(newPass.getText())){
            if(newPass.getText() == null ? newPass1.getText() == null : newPass.getText().equals(newPass1.getText())){ 
                changePass(newPass.getText());
                JOptionPane.showMessageDialog(null, "Done");
            }
            else{
                JOptionPane.showMessageDialog(null, "Password should match!");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Password cannot be blank!", "Retry",1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        // TODO add your handling code here:
        if(jToggleButton1.isSelected()){
            hidd.setVisible(true);
        }
        else{
            hidd.setVisible(false);
        }
    }//GEN-LAST:event_jToggleButton1MouseClicked

    public void changePass(String pass){
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/se_proj","root","");
            pst = conn.prepareStatement("UPDATE CUSTOMER SET C_PASS = ? WHERE C_ID = ?;");
            pst.setString(1, pass);
            pst.setString(2, text1.getText());
            pst.execute();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(custProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(custProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(custProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(custProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new custProfile().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel hidd;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField newPass;
    private javax.swing.JTextField newPass1;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel text4;
    private javax.swing.JLabel text5;
    private javax.swing.JLabel text6;
    // End of variables declaration//GEN-END:variables
}
